export const alumniRecommendations = [
  {
    id: 1,
    name: 'Ravi Kumar',
    photo: 'https://randomuser.me/api/portraits/men/1.jpg',
    company: 'Google',
    position: 'Senior Software Engineer',
    batch: {
      joining: '2014',
      graduation: '2018',
    },
    department: 'CSE',
    location: 'Bangalore, India',
    industry: 'Technology',
    skills: ['React', 'Node.js', 'Cloud Computing'],
    isConnected: false,
    connection: '173',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    photo: 'https://randomuser.me/api/portraits/women/2.jpg',
    company: 'Microsoft',
    position: 'Product Manager',
    batch: {
      joining: '2015',
      graduation: '2019',
    },
    department: 'IT',
    location: 'Hyderabad, India',
    industry: 'Software',
    skills: ['Product Management', 'Agile', 'Data Analytics'],
    isConnected: true,
    connection: '299',
  },
  {
    id: 3,
    name: 'Amit Patel',
    photo: 'https://randomuser.me/api/portraits/men/3.jpg',
    company: 'Amazon',
    position: 'Data Scientist',
    batch: {
      joining: '2013',
      graduation: '2017',
    },
    department: 'CSE',
    location: 'Mumbai, India',
    industry: 'E-commerce',
    skills: ['Python', 'Machine Learning', 'Data Analysis'],
    isConnected: false,
    connection: '87',
  },
  {
    id: 4,
    name: 'Neha Gupta',
    photo: 'https://randomuser.me/api/portraits/women/4.jpg',
    company: 'Flipkart',
    position: 'Backend Developer',
    batch: {
      joining: '2016',
      graduation: '2020',
    },
    department: 'CE',
    location: 'Delhi, India',
    industry: 'E-commerce',
    skills: ['Java', 'Spring Boot', 'Microservices'],
    isConnected: true,
    connection: '42',
  },
  {
    id: 5,
    name: 'Anjali Mehta',
    photo: 'https://randomuser.me/api/portraits/women/5.jpg',
    company: 'TCS',
    position: 'Project Manager',
    batch: {
      joining: '2012',
      graduation: '2016',
    },
    department: 'IT',
    location: 'Pune, India',
    industry: 'IT Services',
    skills: ['Project Management', 'Agile', 'Scrum'],
    isConnected: false,
    connection: '150',
  },
  {
    id: 6,
    name: 'Vikram Singh',
    photo: 'https://randomuser.me/api/portraits/men/6.jpg',
    company: 'Infosys',
    position: 'Full Stack Developer',
    batch: {
      joining: '2015',
      graduation: '2019',
    },
    department: 'CSE',
    location: 'Chennai, India',
    industry: 'IT Services',
    skills: ['JavaScript', 'React', 'Node.js'],
    isConnected: true,
    connection: '200',
  },
  {
    id: 7,
    name: 'Kavita Rao',
    photo: 'https://randomuser.me/api/portraits/women/7.jpg',
    company: 'Wipro',
    position: 'UI/UX Designer',
    batch: {
      joining: '2014',
      graduation: '2018',
    },
    department: 'EXTC',
    location: 'Bangalore, India',
    industry: 'IT Services',
    skills: ['Sketch', 'Figma', 'User Research'],
    isConnected: false,
    connection: '120',
  },
  {
    id: 8,
    name: 'Suresh Reddy',
    photo: 'https://randomuser.me/api/portraits/men/8.jpg',
    company: 'HCL',
    position: 'DevOps Engineer',
    batch: {
      joining: '2013',
      graduation: '2017',
    },
    department: 'ENTC',
    location: 'Noida, India',
    industry: 'IT Services',
    skills: ['Docker', 'Kubernetes', 'AWS'],
    isConnected: true,
    connection: '180',
  },
  {
    id: 9,
    name: 'Rahul Verma',
    photo: 'https://randomuser.me/api/portraits/men/9.jpg',
    company: 'Tech Mahindra',
    position: 'Business Analyst',
    batch: {
      joining: '2012',
      graduation: '2016',
    },
    department: 'ETRX',
    location: 'Hyderabad, India',
    industry: 'IT Services',
    skills: ['Business Analysis', 'SQL', 'Data Visualization'],
    isConnected: false,
    connection: '90',
  },
  {
    id: 10,
    name: 'Pooja Desai',
    photo: 'https://randomuser.me/api/portraits/women/10.jpg',
    company: 'Capgemini',
    position: 'Cloud Architect',
    batch: {
      joining: '2011',
      graduation: '2015',
    },
    department: 'CSE',
    location: 'Pune, India',
    industry: 'IT Services',
    skills: ['AWS', 'Azure', 'Cloud Architecture'],
    isConnected: true,
    connection: '110',
  },
];

export const getAlumniFilters = (data) => {
  const filters = {
    joiningYear: [...new Set(data.map((alumni) => alumni.batch.joining))].sort(),
    graduationYear: [...new Set(data.map((alumni) => alumni.batch.graduation))].sort(),
    location: [...new Set(data.map((alumni) => alumni.location))],
    industry: [...new Set(data.map((alumni) => alumni.industry))],
    department: [...new Set(data.map((alumni) => alumni.department))],
    skills: [...new Set(data.flatMap((alumni) => alumni.skills))].sort(),
  };

  return {
    'Joining Year': filters.joiningYear,
    'Graduation Year': filters.graduationYear,
    Location: filters.location,
    Industry: filters.industry,
    Department: filters.department,
    Skills: filters.skills,
  };
};
