export const eventsData = [
  {
    id: '1',
    title: 'Global Tech Summit 2024',
    location: 'Mumbai Convention Center',
    date: '25th December 2024',
    time: '10:00 AM - 6:00 PM',
    type: 'Conference',
    price: 'Free for Alumni',
    image: 'https://example.com/tech-summit.jpg',
    speakers: [
      {
        name: 'Sundar Pichai',
        role: 'CEO, Google',
        company: 'Google',
        image: 'https://example.com/speaker1.jpg',
      },
      {
        name: 'Satya Nadella',
        role: 'CEO, Microsoft',
        company: 'Microsoft',
        image: 'https://example.com/speaker2.jpg',
      },
    ],
    agenda: 'The summit will cover keynotes on emerging technologies, with speeches from global leaders on AI, Cloud Computing, and the Future of Tech.',
    sponsors: ['Google', 'Microsoft', 'Amazon'],
    registeredCount: 1500,
    maxCapacity: 2000,
  },
  {
    id: '2',
    title: 'Sustainability Summit 2024',
    location: 'New Delhi Expo Center',
    date: '15th January 2025',
    time: '9:00 AM - 4:00 PM',
    type: 'Seminar',
    price: '₹1000',
    image: 'https://example.com/sustainability-summit.jpg',
    speakers: [
      {
        name: 'Greta Thunberg',
        role: 'Environmental Activist',
        company: 'Fridays for Future',
        image: 'https://example.com/speaker3.jpg',
      },
      {
        name: 'Elon Musk',
        role: 'CEO, Tesla',
        company: 'Tesla',
        image: 'https://example.com/speaker4.jpg',
      },
    ],
    agenda: 'The seminar will focus on climate change and the future of electric vehicles, with discussions on sustainable energy practices.',
    sponsors: ['Tesla', 'IKEA', 'UNICEF'],
    registeredCount: 800,
    maxCapacity: 1000,
  },
  {
    id: '3',
    title: 'Blockchain World Expo 2025',
    location: 'Hyderabad Tech Arena',
    date: '5th February 2025',
    time: '11:00 AM - 6:00 PM',
    type: 'Expo',
    price: '₹1500',
    image: 'https://example.com/blockchain-expo.jpg',
    speakers: [
      {
        name: 'Vitalik Buterin',
        role: 'Co-founder',
        company: 'Ethereum',
        image: 'https://example.com/speaker5.jpg',
      },
      {
        name: 'Changpeng Zhao',
        role: 'CEO',
        company: 'Binance',
        image: 'https://example.com/speaker6.jpg',
      },
    ],
    agenda: 'The expo will cover Ethereum 2.0 updates and discuss the future of cryptocurrency exchanges, with insights into blockchain scalability and security.',
    sponsors: ['Ethereum Foundation', 'Binance', 'Coinbase'],
    registeredCount: 900,
    maxCapacity: 1200,
  },
  {
    id: '4',
    title: 'Design Thinking Workshop',
    location: 'Bangalore Creative Hub',
    date: '10th March 2025',
    time: '10:00 AM - 5:00 PM',
    type: 'Workshop',
    price: '₹500',
    image: 'https://example.com/design-workshop.jpg',
    speakers: [
      {
        name: 'Don Norman',
        role: 'Author, Design of Everyday Things',
        company: 'Nielsen Norman Group',
        image: 'https://example.com/speaker7.jpg',
      },
      {
        name: 'Tim Brown',
        role: 'Chairman',
        company: 'IDEO',
        image: 'https://example.com/speaker8.jpg',
      },
    ],
    agenda: 'The workshop will explore the principles of Design Thinking, offering practical methods for solving business problems through creative innovation.',
    sponsors: ['IDEO', 'Adobe', 'Figma'],
    registeredCount: 600,
    maxCapacity: 800,
  },
  {
    id: '5',
    title: 'Future of Space Exploration',
    location: 'ISRO Headquarters, Bangalore',
    date: '20th April 2025',
    time: '9:00 AM - 3:00 PM',
    type: 'Conference',
    price: '₹1200',
    image: 'https://example.com/space-exploration.jpg',
    speakers: [
      {
        name: 'Dr. K. Sivan',
        role: 'Former Chairman',
        company: 'ISRO',
        image: 'https://example.com/speaker9.jpg',
      },
      {
        name: 'Chris Hadfield',
        role: 'Astronaut',
        company: 'Canadian Space Agency',
        image: 'https://example.com/speaker10.jpg',
      },
    ],
    agenda: 'The conference will explore India’s space achievements and offer insights into the future of Mars exploration and the challenges of living on Mars.',
    sponsors: ['ISRO', 'NASA', 'SpaceX'],
    registeredCount: 700,
    maxCapacity: 1000,
  },
];
