export const jobsData = [
  {
    id: '1',
    title: 'Senior Software Engineer',
    company: 'Google India',
    logo: 'https://logo.clearbit.com/google.com',
    location: 'Bangalore, India (Hybrid)',
    salary: '₹35,00,000 - ₹55,00,000',
    type: 'Full-time',
    experience: '5-8 years',
    skills: ['React', 'Node.js', 'Cloud Architecture', 'System Design', 'Go'],
    benefits: ['Health Insurance', 'Stock Options', 'Flexible Hours', 'Remote Work'],
    description: 'Join our core engineering team to build next-gen cloud products...',
    postedDate: '2024-01-15',
    department: 'Engineering',
    vacancies: 3,
    requirements: [
      'B.Tech/M.Tech in Computer Science',
      'Experience with distributed systems',
      'Strong problem-solving skills',
    ],
    jdPdf: 'https://drive.google.com/drive/folders/1zxeuugiiSbTLxTZTEh6dkAbmJ83ih-_R',
    postedBy: {
      name: 'John Doe',
    },
  },
  {
    id: '2',
    title: 'AI/ML Research Scientist',
    company: 'Microsoft Research',
    logo: 'https://logo.clearbit.com/microsoft.com',
    location: 'Hyderabad, India',
    salary: '₹45,00,000 - ₹75,00,000',
    type: 'Full-time',
    experience: '3-6 years',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'NLP', 'Computer Vision'],
    benefits: ['Relocation Assistance', 'Research Budget', 'Conference Travel'],
    postedDate: '2024-01-20',
    department: 'Research & Development',
    jdPdf: 'https://example.com/jd/microsoft-ai-ml-research-scientist.pdf',
    postedBy: {
      name: 'Alice Smith',
    },
  },
  {
    id: '3',
    title: 'Data Scientist',
    company: 'Amazon India',
    logo: 'https://logo.clearbit.com/amazon.com',
    location: 'Bangalore, India',
    salary: '₹25,00,000 - ₹50,00,000',
    type: 'Full-time',
    experience: '2-5 years',
    skills: ['Machine Learning', 'Python', 'SQL', 'Data Visualization'],
    benefits: ['Health Insurance', 'Paid Time Off', 'Team Outings'],
    description: 'Join our Data Science team to work on cutting-edge projects...',
    postedDate: '2024-02-10',
    department: 'Data Science',
    vacancies: 2,
    requirements: [
      'B.Tech/M.Tech in Data Science or related field',
      'Proven experience in statistical modeling and data analysis',
    ],
    jdPdf: 'https://example.com/jd/amazon-data-scientist.pdf',
    postedBy: {
      name: 'Bob Johnson',
    },
  },
  {
    id: '4',
    title: 'Frontend Developer',
    company: 'Adobe Systems',
    logo: 'https://logo.clearbit.com/adobe.com',
    location: 'Noida, India',
    salary: '₹15,00,000 - ₹30,00,000',
    type: 'Full-time',
    experience: '3-5 years',
    skills: ['JavaScript', 'React', 'CSS', 'HTML'],
    benefits: ['Stock Options', 'Paid Leave', 'Flexible Work Hours'],
    description: 'Looking for a passionate Frontend Developer to join our team...',
    postedDate: '2024-02-25',
    department: 'Engineering',
    vacancies: 4,
    requirements: [
      'Experience with frontend technologies (React, HTML, CSS)',
      'Strong understanding of UX/UI principles',
    ],
    jdPdf: 'https://example.com/jd/adobe-frontend-developer.pdf',
    postedBy: {
      name: 'Charlie Lee',
    },
  },
  {
    id: '5',
    title: 'Backend Developer',
    company: 'Flipkart',
    logo: 'https://logo.clearbit.com/flipkart.com',
    location: 'Bangalore, India',
    salary: '₹20,00,000 - ₹45,00,000',
    type: 'Full-time',
    experience: '4-6 years',
    skills: ['Java', 'Spring Boot', 'Microservices', 'AWS'],
    benefits: ['Health Insurance', 'Work From Home', 'Annual Bonus'],
    description: 'Join our Backend team to scale high-performance systems...',
    postedDate: '2024-03-05',
    department: 'Engineering',
    vacancies: 5,
    requirements: [
      'Experience with Java, Spring Boot, and Microservices architecture',
      'Familiarity with cloud platforms like AWS or Azure',
    ],
    jdPdf: 'https://example.com/jd/flipkart-backend-developer.pdf',
    postedBy: {
      name: 'David Williams',
    },
  },
  {
    id: '6',
    title: 'Product Manager',
    company: 'LinkedIn',
    logo: 'https://logo.clearbit.com/linkedin.com',
    location: 'Mumbai, India',
    salary: '₹40,00,000 - ₹70,00,000',
    type: 'Full-time',
    experience: '5-10 years',
    skills: ['Product Strategy', 'Agile Methodology', 'Market Research'],
    benefits: ['Relocation Support', 'Health Benefits', 'Work-Life Balance'],
    description: 'Lead our product development and innovation initiatives...',
    postedDate: '2024-03-10',
    department: 'Product',
    vacancies: 2,
    requirements: [
      'MBA or equivalent experience in Product Management',
      'Strong communication and leadership skills',
    ],
    jdPdf: 'https://example.com/jd/linkedin-product-manager.pdf',
    postedBy: {
      name: 'Eve Davis',
    },
  },
  {
    id: '7',
    title: 'UX/UI Designer',
    company: 'Airbnb',
    logo: 'https://logo.clearbit.com/airbnb.com',
    location: 'Delhi, India',
    salary: '₹25,00,000 - ₹50,00,000',
    type: 'Full-time',
    experience: '3-6 years',
    skills: ['Sketch', 'Figma', 'User Research', 'Prototyping'],
    benefits: ['Stock Options', 'Paid Time Off', 'Collaborative Team Environment'],
    description: 'Join our design team to create world-class user experiences...',
    postedDate: '2024-03-15',
    department: 'Design',
    vacancies: 3,
    requirements: [
      'Proven experience in UX/UI design',
      'Strong portfolio showcasing design work',
    ],
    jdPdf: 'https://example.com/jd/airbnb-ux-ui-designer.pdf',
    postedBy: {
      name: 'Frank Moore',
    },
  },
  {
    id: '8',
    title: 'Full Stack Developer',
    company: 'Zomato',
    logo: 'https://logo.clearbit.com/zomato.com',
    location: 'Gurugram, India',
    salary: '₹25,00,000 - ₹40,00,000',
    type: 'Full-time',
    experience: '3-6 years',
    skills: ['React', 'Node.js', 'Express', 'MongoDB'],
    benefits: ['Paid Sick Leave', 'Health Benefits', 'Flexible Work Schedule'],
    description: 'Work on building scalable and efficient full-stack systems...',
    postedDate: '2024-03-20',
    department: 'Engineering',
    vacancies: 4,
    requirements: [
      'Experience with JavaScript, React, Node.js, and MongoDB',
      'Strong understanding of both frontend and backend technologies',
    ],
    jdPdf: 'https://example.com/jd/zomato-full-stack-developer.pdf',
    postedBy: {
      name: 'Grace Taylor',
    },
  },
  {
    id: '9',
    title: 'DevOps Engineer',
    company: 'Twitter',
    logo: 'https://logo.clearbit.com/twitter.com',
    location: 'Bangalore, India',
    salary: '₹30,00,000 - ₹60,00,000',
    type: 'Full-time',
    experience: '4-8 years',
    skills: ['Docker', 'Kubernetes', 'AWS', 'CI/CD'],
    benefits: ['Work From Home', 'Annual Bonus', 'Professional Development'],
    description: 'Build and maintain our CI/CD pipelines and infrastructure...',
    postedDate: '2024-04-01',
    department: 'Engineering',
    vacancies: 3,
    requirements: [
      'Experience with containerization and orchestration tools like Docker and Kubernetes',
      'Strong knowledge of AWS and cloud technologies',
    ],
    jdPdf: 'https://example.com/jd/twitter-devops-engineer.pdf',
    postedBy: {
      name: 'Henry Brown',
    },
  },
  {
    id: '10',
    title: 'Cloud Solutions Architect',
    company: 'Oracle',
    logo: 'https://logo.clearbit.com/oracle.com',
    location: 'Hyderabad, India',
    salary: '₹40,00,000 - ₹80,00,000',
    type: 'Full-time',
    experience: '5-10 years',
    skills: ['Cloud Computing', 'AWS', 'Azure', 'Terraform'],
    benefits: ['Paid Time Off', 'Health Insurance', 'Remote Work Opportunities'],
    description: 'Design and implement cloud architectures for enterprise solutions...',
    postedDate: '2024-04-05',
    department: 'Engineering',
    vacancies: 2,
    requirements: [
      'Experience designing cloud solutions with AWS or Azure',
      'Strong knowledge of infrastructure as code using Terraform',
    ],
    jdPdf: 'https://example.com/jd/oracle-cloud-solutions-architect.pdf',
    postedBy: {
      name: 'Ivy Green',
    },
  },
];
