import profileImg from '../assets/profile.jpg';

export const alumniMapData = [
  // Users in India
  {
    id: 1,
    name: 'Ravi Kumar',
    latitude: 28.6139,
    longitude: 77.209,
    profilePhoto: profileImg,
  },
  {
    id: 2,
    name: 'Priya Sharma',
    latitude: 19.076,
    longitude: 72.8777,
    profilePhoto: profileImg,
  },
  {
    id: 3,
    name: 'Amit Patel',
    latitude: 12.9716,
    longitude: 77.5946,
    profilePhoto: profileImg,
  },
  {
    id: 4,
    name: 'Neha Gupta',
    latitude: 22.5726,
    longitude: 88.3639,
    profilePhoto: profileImg,
  },
  {
    id: 5,
    name: 'Anjali Mehta',
    latitude: 13.0827,
    longitude: 80.2707,
    profilePhoto: profileImg,
  },
  {
    id: 6,
    name: 'Vikram Singh',
    latitude: 17.385044,
    longitude: 78.486671,
    profilePhoto: profileImg,
  },
  {
    id: 7,
    name: 'Kavita Rao',
    latitude: 23.0225,
    longitude: 72.5714,
    profilePhoto: profileImg,
  },
  {
    id: 8,
    name: 'Suresh Reddy',
    latitude: 26.8467,
    longitude: 80.9462,
    profilePhoto: profileImg,
  },
  {
    id: 9,
    name: 'Rahul Verma',
    latitude: 28.7041,
    longitude: 77.1025,
    profilePhoto: profileImg,
  },
  {
    id: 10,
    name: 'Pooja Desai',
    latitude: 19.2183,
    longitude: 84.7915,
    profilePhoto: profileImg,
  },
  // Users outside of India
  {
    id: 11,
    name: 'Arjun Nair',
    latitude: 31.5497,
    longitude: 74.3436,
    profilePhoto: profileImg,
  },
  {
    id: 12,
    name: 'Meera Iyer',
    latitude: 51.5074,
    longitude: -0.1278,
    profilePhoto: profileImg,
  },
  {
    id: 13,
    name: 'Rohan Das',
    latitude: 40.7128,
    longitude: -74.006,
    profilePhoto: profileImg,
  },
  {
    id: 14,
    name: 'Sneha Kapoor',
    latitude: 48.8566,
    longitude: 2.3522,
    profilePhoto: profileImg,
  },
  {
    id: 15,
    name: 'Vivek Malhotra',
    latitude: 34.0522,
    longitude: -118.2437,
    profilePhoto: profileImg,
  },
  {
    id: 16,
    name: 'Nisha Jain',
    latitude: 52.52,
    longitude: 13.405,
    profilePhoto: profileImg,
  },
  {
    id: 17,
    name: 'Rajesh Singh',
    latitude: 40.7306,
    longitude: -73.9352,
    profilePhoto: profileImg,
  },
  {
    id: 18,
    name: 'Pallavi Rao',
    latitude: 43.65107,
    longitude: -79.347015,
    profilePhoto: profileImg,
  },
  {
    id: 19,
    name: 'Karan Mehta',
    latitude: -33.8688,
    longitude: 151.2093,
    profilePhoto: profileImg,
  },
  {
    id: 20,
    name: 'Ritika Sharma',
    latitude: 35.6895,
    longitude: 139.6917,
    profilePhoto: profileImg,
  },
];

export const alumniRecommendations = [
  {
    id: 1,
    name: 'Ravi Kumar',
    photo: profileImg,
    company: 'Google',
    position: 'Senior Software Engineer',
    batch: {
      joining: '2014',
      graduation: '2018',
    },
    department: 'CSE',
    location: 'Bangalore, India',
    industry: 'Technology',
    skills: ['React', 'Node.js', 'Cloud Computing'],
    isConnected: false,
    connection: '173 other mutual connections',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    photo: profileImg,
    company: 'Microsoft',
    position: 'Product Manager',
    batch: {
      joining: '2015',
      graduation: '2019',
    },
    department: 'IT',
    location: 'Hyderabad, India',
    industry: 'Software',
    skills: ['Product Management', 'Agile', 'Data Analytics'],
    isConnected: true,
    connection: '299 other mutual connections',
  },
  {
    id: 3,
    name: 'Amit Patel',
    photo: profileImg,
    company: 'Amazon',
    position: 'Data Scientist',
    batch: {
      joining: '2013',
      graduation: '2017',
    },
    department: 'CSE',
    location: 'Mumbai, India',
    industry: 'E-commerce',
    skills: ['Python', 'Machine Learning', 'Data Analysis'],
    isConnected: false,
    connection: '87 other mutual connections',
  },
  {
    id: 4,
    name: 'Neha Gupta',
    photo: profileImg,
    company: 'Flipkart',
    position: 'Backend Developer',
    batch: {
      joining: '2016',
      graduation: '2020',
    },
    department: 'CE',
    location: 'Delhi, India',
    industry: 'E-commerce',
    skills: ['Java', 'Spring Boot', 'Microservices'],
    isConnected: true,
    connection: '42 other mutual connections',
  },
  {
    id: 5,
    name: 'Anjali Mehta',
    photo: profileImg,
    company: 'TCS',
    position: 'Project Manager',
    batch: {
      joining: '2012',
      graduation: '2016',
    },
    department: 'IT',
    location: 'Pune, India',
    industry: 'IT Services',
    skills: ['Project Management', 'Agile', 'Scrum'],
    isConnected: false,
    connection: '150 other mutual connections',
  },
  {
    id: 6,
    name: 'Vikram Singh',
    photo: profileImg,
    company: 'Infosys',
    position: 'Full Stack Developer',
    batch: {
      joining: '2015',
      graduation: '2019',
    },
    department: 'CSE',
    location: 'Chennai, India',
    industry: 'IT Services',
    skills: ['JavaScript', 'React', 'Node.js'],
    isConnected: true,
    connection: '200 other mutual connections',
  },
  {
    id: 7,
    name: 'Kavita Rao',
    photo: profileImg,
    company: 'Wipro',
    position: 'UI/UX Designer',
    batch: {
      joining: '2014',
      graduation: '2018',
    },
    department: 'EXTC',
    location: 'Bangalore, India',
    industry: 'IT Services',
    skills: ['Sketch', 'Figma', 'User Research'],
    isConnected: false,
    connection: '120 other mutual connections',
  },
  {
    id: 8,
    name: 'Suresh Reddy',
    photo: profileImg,
    company: 'HCL',
    position: 'DevOps Engineer',
    batch: {
      joining: '2013',
      graduation: '2017',
    },
    department: 'ENTC',
    location: 'Noida, India',
    industry: 'IT Services',
    skills: ['Docker', 'Kubernetes', 'AWS'],
    isConnected: true,
    connection: '180 other mutual connections',
  },
  {
    id: 9,
    name: 'Rahul Verma',
    photo: profileImg,
    company: 'Tech Mahindra',
    position: 'Business Analyst',
    batch: {
      joining: '2012',
      graduation: '2016',
    },
    department: 'ETRX',
    location: 'Hyderabad, India',
    industry: 'IT Services',
    skills: ['Business Analysis', 'SQL', 'Data Visualization'],
    isConnected: false,
    connection: '90 other mutual connections',
  },
  {
    id: 10,
    name: 'Pooja Desai',
    photo: profileImg,
    company: 'Capgemini',
    position: 'Cloud Architect',
    batch: {
      joining: '2011',
      graduation: '2015',
    },
    department: 'CSE',
    location: 'Pune, India',
    industry: 'IT Services',
    skills: ['AWS', 'Azure', 'Cloud Architecture'],
    isConnected: true,
    connection: '110 other mutual connections',
  },
];

export const getAlumniFilters = (data) => {
  const filters = {
    joiningYear: [...new Set(data.map((alumni) => alumni.batch.joining))].sort(),
    graduationYear: [...new Set(data.map((alumni) => alumni.batch.graduation))].sort(),
    location: [...new Set(data.map((alumni) => alumni.location))],
    industry: [...new Set(data.map((alumni) => alumni.industry))],
    department: [...new Set(data.map((alumni) => alumni.department))],
    skills: [...new Set(data.flatMap((alumni) => alumni.skills))].sort(),
  };

  return {
    'Joining Year': filters.joiningYear,
    'Graduation Year': filters.graduationYear,
    Location: filters.location,
    Industry: filters.industry,
    Department: filters.department,
    Skills: filters.skills,
  };
};
