export const jobsData = [
  {
    id: '1',
    title: 'Senior Software Engineer',
    company: 'Google India',
    logo: 'https://logo.clearbit.com/google.com',
    location: 'Bangalore, India (Hybrid)',
    salary: '₹35,00,000 - ₹55,00,000',
    type: 'Full-time',
    experience: '5-8 years',
    skills: ["React Native", "JavaScript", "Python", "AWS", "UI/UX Design"],
    benefits: ['Health Insurance', 'Stock Options', 'Flexible Hours', 'Remote Work'],
    description: 'Join our core engineering team to build next-gen cloud products...',
    postedDate: '2024-01-15',
    department: 'Engineering',
    vacancies: 3,
    requirements: [
      'B.Tech/M.Tech in Computer Science',
      'Experience with distributed systems',
      'Strong problem-solving skills',
    ],
  },
  {
    id: '2',
    title: 'AI/ML Research Scientist',
    company: 'Microsoft Research',
    logo: 'https://logo.clearbit.com/microsoft.com',
    location: 'Hyderabad, India',
    salary: '₹45,00,000 - ₹75,00,000',
    type: 'Full-time',
    experience: '3-6 years',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'NLP', 'Computer Vision'],
    benefits: ['Relocation Assistance', 'Research Budget', 'Conference Travel'],
    postedDate: '2024-01-20',
  },
  {
    id: '3',
    title: 'Machine Learning Engineer',
    company: 'Apple India',
    logo: 'https://logo.clearbit.com/apple.com',
    location: 'Bangalore, India',
    salary: '₹40,00,000 - ₹65,00,000',
    type: 'Full-time',
    experience: '4-7 years',
    skills: ['Python', 'Core ML', 'Deep Learning', 'iOS Development', 'Swift'],
    benefits: ['Health Insurance', 'RSUs', 'Gym Membership', 'Food Allowance'],
    description: 'Work on cutting-edge ML solutions for Apple products...',
    postedDate: '2024-01-18',
    department: 'AI/ML',
    vacancies: 2,
    requirements: ['Masters in ML/AI', 'iOS platform experience', 'Published research papers'],
  },
  {
    id: '4',
    title: 'GPU Architecture Engineer',
    company: 'NVIDIA India',
    logo: 'https://logo.clearbit.com/nvidia.com',
    location: 'Pune, India',
    salary: '₹50,00,000 - ₹80,00,000',
    type: 'Full-time',
    experience: '6-10 years',
    skills: ['CUDA', 'Computer Architecture', 'RTL Design', 'C++','JavaScript', 'Performance Optimization'],
    benefits: ['Stock Benefits', 'Education Reimbursement', 'Health Coverage'],
    description: 'Design next-generation GPU architectures...',
    postedDate: '2024-01-22',
    department: 'Hardware Engineering',
    vacancies: 4,
    requirements: ['PhD in Computer Engineering preferred', 'GPU design experience'],
  },
  {
    id: '5',
    title: 'Senior Android Developer',
    company: 'Samsung R&D',
    logo: 'https://logo.clearbit.com/samsung.com',
    location: 'Noida, India',
    salary: '₹25,00,000 - ₹45,00,000',
    type: 'Full-time',
    experience: '4-8 years',
    skills: ['Android', 'Kotlin', 'Java', 'OneUI Development', 'Mobile Security'],
    benefits: ['Insurance', 'Phone Benefits', 'Flexible Work Hours'],
    description: 'Lead Android development for Samsung devices...',
    postedDate: '2024-01-25',
    department: 'Mobile Development',
    vacancies: 5,
    requirements: ['Android expertise', 'UI/UX knowledge', 'System optimization skills'],
  },
  {
    id: '6',
    title: 'Autonomous Driving Engineer',
    company: 'Tesla India',
    logo: 'https://logo.clearbit.com/tesla.com',
    location: 'Bangalore, India',
    salary: '₹60,00,000 - ₹90,00,000',
    type: 'Full-time',
    experience: '5-9 years',
    skills: ['Computer Vision', 'C++', 'Python', 'ROS', 'Sensor Fusion'],
    benefits: ['Tesla Vehicle Discount', 'Stock Options', 'Insurance'],
    description: 'Develop autonomous driving capabilities...',
    postedDate: '2024-01-28',
    department: 'Autopilot',
    vacancies: 3,
    requirements: ['Masters/PhD in Robotics/AI', 'Experience with autonomous systems'],
  },
  {
    id: '7',
    title: 'AR/VR Software Engineer',
    company: 'Meta India',
    logo: 'https://logo.clearbit.com/meta.com',
    location: 'Hyderabad, India',
    salary: '₹35,00,000 - ₹60,00,000',
    type: 'Full-time',
    experience: '3-7 years',
    skills: ['Unity3D', 'C#', 'Computer Graphics', 'OpenGL', 'AR Kit'],
    benefits: ['Meta Hardware Access', 'Insurance', 'Wellness Programs'],
    description: 'Build next-generation AR/VR experiences...',
    postedDate: '2024-01-30',
    department: 'Reality Labs',
    vacancies: 4,
    requirements: ['Graphics programming expertise', '3D math skills'],
  },
  {
    id: '8',
    title: 'Software Integration Engineer',
    company: 'Audi India',
    logo: 'https://logo.clearbit.com/audi.com',
    location: 'Pune, India',
    salary: '₹20,00,000 - ₹40,00,000',
    type: 'Full-time',
    experience: '3-6 years',
    skills: ['Embedded Systems', 'AUTOSAR', 'C++', 'CAN Protocol', 'Vehicle Networks'],
    benefits: ['Car Lease Options', 'Insurance', 'Professional Training'],
    description: 'Develop automotive software solutions...',
    postedDate: '2024-02-01',
    department: 'Automotive Software',
    vacancies: 6,
    requirements: ['Automotive software experience', 'ECU programming knowledge'],
  },
  {
    id: '9',
    title: 'Privacy Engineer',
    company: 'Facebook India',
    logo: 'https://logo.clearbit.com/facebook.com',
    location: 'Mumbai, India',
    salary: '₹30,00,000 - ₹50,00,000',
    type: 'Full-time',
    experience: '4-7 years',
    skills: ['Data Privacy', 'Security Protocols', 'Python', 'GDPR', 'Encryption'],
    benefits: ['Health Insurance', 'Stock Options', 'Food & Transport'],
    description: 'Ensure data privacy in Facebook products...',
    postedDate: '2024-02-03',
    department: 'Privacy & Security',
    vacancies: 2,
    requirements: ['Security certification', 'Privacy framework knowledge'],
  },
  {
    id: '10',
    title: 'DevOps Engineer',
    company: 'Apple India',
    logo: 'https://logo.clearbit.com/apple.com',
    location: 'Hyderabad, India',
    salary: '₹25,00,000 - ₹45,00,000',
    type: 'Full-time',
    experience: '3-6 years',
    skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Infrastructure as Code'],
    benefits: ['Health Coverage', 'Stock Units', 'Fitness Center'],
    description: 'Manage cloud infrastructure for Apple services...',
    postedDate: '2024-02-05',
    department: 'Cloud Services',
    vacancies: 4,
    requirements: ['Cloud certification', 'Automation experience'],
  }
];
